/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'PropertyNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyNFT__factory>
getContractFactory(name: 'RentalAgreement', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RentalAgreement__factory>
getContractFactory(name: 'RentalNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RentalNFT__factory>
getContractFactory(name: 'RentalAgreementFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RentalAgreementFactory__factory>
getContractFactory(name: 'IERC4907', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC4907__factory>
getContractFactory(name: 'IPropertyNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPropertyNFT__factory>
getContractFactory(name: 'IRentalAgreement', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRentalAgreement__factory>
getContractFactory(name: 'IRentalAgreementFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRentalAgreementFactory__factory>
getContractFactory(name: 'IRentalNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRentalNFT__factory>
getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>

  getContractAt(name: 'PropertyNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyNFT>
getContractAt(name: 'RentalAgreement', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RentalAgreement>
getContractAt(name: 'RentalNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RentalNFT>
getContractAt(name: 'RentalAgreementFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RentalAgreementFactory>
getContractAt(name: 'IERC4907', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC4907>
getContractAt(name: 'IPropertyNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPropertyNFT>
getContractAt(name: 'IRentalAgreement', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRentalAgreement>
getContractAt(name: 'IRentalAgreementFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRentalAgreementFactory>
getContractAt(name: 'IRentalNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRentalNFT>
getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>

  deployContract(name: 'PropertyNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyNFT>
deployContract(name: 'RentalAgreement', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalAgreement>
deployContract(name: 'RentalNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalNFT>
deployContract(name: 'RentalAgreementFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalAgreementFactory>
deployContract(name: 'IERC4907', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC4907>
deployContract(name: 'IPropertyNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPropertyNFT>
deployContract(name: 'IRentalAgreement', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalAgreement>
deployContract(name: 'IRentalAgreementFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalAgreementFactory>
deployContract(name: 'IRentalNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalNFT>
deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

  deployContract(name: 'PropertyNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyNFT>
deployContract(name: 'RentalAgreement', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalAgreement>
deployContract(name: 'RentalNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalNFT>
deployContract(name: 'RentalAgreementFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RentalAgreementFactory>
deployContract(name: 'IERC4907', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC4907>
deployContract(name: 'IPropertyNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPropertyNFT>
deployContract(name: 'IRentalAgreement', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalAgreement>
deployContract(name: 'IRentalAgreementFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalAgreementFactory>
deployContract(name: 'IRentalNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRentalNFT>
deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  