/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RentalAgreementInterface extends Interface {
    getFunction(nameOrSignature: "approveAgreement" | "baseRent" | "cancelAgreement" | "checkExpiration" | "claimDeposit" | "completeAgreement" | "deadline" | "declareDefault" | "depositStatus" | "duration" | "factory" | "gracePeriod" | "inflationAdjustmentInterval" | "inflationBps" | "landlord" | "landlordApproved" | "landlordCancelled" | "lateFeeBps" | "payRent" | "paymentPeriod" | "propertyId" | "propertyNFT" | "releaseDeposit" | "rentPaidUntil" | "rentalNFT" | "securityDeposit" | "startTime" | "status" | "tenant" | "tenantApproved" | "tenantCancelled" | "usdcToken" | "withdrawRent"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgreementActivated" | "AgreementCancelled" | "AgreementCompleted" | "AgreementDefaulted" | "AgreementExpired" | "AgreementPending" | "DepositClaimed" | "DepositLocked" | "DepositReleased" | "LandlordApproved" | "LateFeeApplied" | "RentPaid" | "TenantApproved"): EventFragment;

    encodeFunctionData(functionFragment: 'approveAgreement', values?: undefined): string;
encodeFunctionData(functionFragment: 'baseRent', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelAgreement', values?: undefined): string;
encodeFunctionData(functionFragment: 'checkExpiration', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimDeposit', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'completeAgreement', values?: undefined): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'declareDefault', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'duration', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'gracePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'inflationAdjustmentInterval', values?: undefined): string;
encodeFunctionData(functionFragment: 'inflationBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlord', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlordApproved', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlordCancelled', values?: undefined): string;
encodeFunctionData(functionFragment: 'lateFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'payRent', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyId', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'rentPaidUntil', values?: undefined): string;
encodeFunctionData(functionFragment: 'rentalNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'securityDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'startTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenant', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenantApproved', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenantCancelled', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawRent', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approveAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkExpiration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'declareDefault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'duration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gracePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inflationAdjustmentInterval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inflationBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlordApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlordCancelled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lateFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentPaidUntil', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentalNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'securityDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenantApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenantCancelled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRent', data: BytesLike): Result;
  }

  
    export namespace AgreementActivatedEvent {
      export type InputTuple = [agreementAddress: AddressLike, propertyId: BigNumberish];
      export type OutputTuple = [agreementAddress: string, propertyId: bigint];
      export interface OutputObject {agreementAddress: string, propertyId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgreementCancelledEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgreementCompletedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgreementDefaultedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgreementExpiredEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgreementPendingEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositClaimedEvent {
      export type InputTuple = [amount: BigNumberish, reason: string];
      export type OutputTuple = [amount: bigint, reason: string];
      export interface OutputObject {amount: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositLockedEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositReleasedEvent {
      export type InputTuple = [amount: BigNumberish];
      export type OutputTuple = [amount: bigint];
      export interface OutputObject {amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LandlordApprovedEvent {
      export type InputTuple = [landlord: AddressLike];
      export type OutputTuple = [landlord: string];
      export interface OutputObject {landlord: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LateFeeAppliedEvent {
      export type InputTuple = [monthIndex: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [monthIndex: bigint, amount: bigint];
      export interface OutputObject {monthIndex: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RentPaidEvent {
      export type InputTuple = [monthIndex: BigNumberish, amount: BigNumberish, lateFeeApplied: BigNumberish];
      export type OutputTuple = [monthIndex: bigint, amount: bigint, lateFeeApplied: bigint];
      export interface OutputObject {monthIndex: bigint, amount: bigint, lateFeeApplied: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TenantApprovedEvent {
      export type InputTuple = [tenant: AddressLike];
      export type OutputTuple = [tenant: string];
      export interface OutputObject {tenant: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RentalAgreement extends BaseContract {
    
    connect(runner?: ContractRunner | null): RentalAgreement;
    waitForDeployment(): Promise<this>;

    interface: RentalAgreementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveAgreement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    baseRent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelAgreement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    checkExpiration: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimDeposit: TypedContractMethod<
      [amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    completeAgreement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    declareDefault: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    depositStatus: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    duration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    gracePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    inflationAdjustmentInterval: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    inflationBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    landlord: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    landlordApproved: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    landlordCancelled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lateFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    payRent: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paymentPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    propertyId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    propertyNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseDeposit: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rentPaidUntil: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rentalNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    securityDeposit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    startTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tenant: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tenantApproved: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    tenantCancelled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawRent: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveAgreement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'baseRent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAgreement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkExpiration'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimDeposit'): TypedContractMethod<
      [amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeAgreement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'declareDefault'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositStatus'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'duration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'gracePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'inflationAdjustmentInterval'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'inflationBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'landlord'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'landlordApproved'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'landlordCancelled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lateFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'payRent'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paymentPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'propertyId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'propertyNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseDeposit'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rentPaidUntil'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rentalNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'securityDeposit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tenant'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tenantApproved'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'tenantCancelled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawRent'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgreementActivated'): TypedContractEvent<AgreementActivatedEvent.InputTuple, AgreementActivatedEvent.OutputTuple, AgreementActivatedEvent.OutputObject>;
getEvent(key: 'AgreementCancelled'): TypedContractEvent<AgreementCancelledEvent.InputTuple, AgreementCancelledEvent.OutputTuple, AgreementCancelledEvent.OutputObject>;
getEvent(key: 'AgreementCompleted'): TypedContractEvent<AgreementCompletedEvent.InputTuple, AgreementCompletedEvent.OutputTuple, AgreementCompletedEvent.OutputObject>;
getEvent(key: 'AgreementDefaulted'): TypedContractEvent<AgreementDefaultedEvent.InputTuple, AgreementDefaultedEvent.OutputTuple, AgreementDefaultedEvent.OutputObject>;
getEvent(key: 'AgreementExpired'): TypedContractEvent<AgreementExpiredEvent.InputTuple, AgreementExpiredEvent.OutputTuple, AgreementExpiredEvent.OutputObject>;
getEvent(key: 'AgreementPending'): TypedContractEvent<AgreementPendingEvent.InputTuple, AgreementPendingEvent.OutputTuple, AgreementPendingEvent.OutputObject>;
getEvent(key: 'DepositClaimed'): TypedContractEvent<DepositClaimedEvent.InputTuple, DepositClaimedEvent.OutputTuple, DepositClaimedEvent.OutputObject>;
getEvent(key: 'DepositLocked'): TypedContractEvent<DepositLockedEvent.InputTuple, DepositLockedEvent.OutputTuple, DepositLockedEvent.OutputObject>;
getEvent(key: 'DepositReleased'): TypedContractEvent<DepositReleasedEvent.InputTuple, DepositReleasedEvent.OutputTuple, DepositReleasedEvent.OutputObject>;
getEvent(key: 'LandlordApproved'): TypedContractEvent<LandlordApprovedEvent.InputTuple, LandlordApprovedEvent.OutputTuple, LandlordApprovedEvent.OutputObject>;
getEvent(key: 'LateFeeApplied'): TypedContractEvent<LateFeeAppliedEvent.InputTuple, LateFeeAppliedEvent.OutputTuple, LateFeeAppliedEvent.OutputObject>;
getEvent(key: 'RentPaid'): TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
getEvent(key: 'TenantApproved'): TypedContractEvent<TenantApprovedEvent.InputTuple, TenantApprovedEvent.OutputTuple, TenantApprovedEvent.OutputObject>;

    filters: {
      
      'AgreementActivated(address,uint256)': TypedContractEvent<AgreementActivatedEvent.InputTuple, AgreementActivatedEvent.OutputTuple, AgreementActivatedEvent.OutputObject>;
      AgreementActivated: TypedContractEvent<AgreementActivatedEvent.InputTuple, AgreementActivatedEvent.OutputTuple, AgreementActivatedEvent.OutputObject>;
    

      'AgreementCancelled()': TypedContractEvent<AgreementCancelledEvent.InputTuple, AgreementCancelledEvent.OutputTuple, AgreementCancelledEvent.OutputObject>;
      AgreementCancelled: TypedContractEvent<AgreementCancelledEvent.InputTuple, AgreementCancelledEvent.OutputTuple, AgreementCancelledEvent.OutputObject>;
    

      'AgreementCompleted()': TypedContractEvent<AgreementCompletedEvent.InputTuple, AgreementCompletedEvent.OutputTuple, AgreementCompletedEvent.OutputObject>;
      AgreementCompleted: TypedContractEvent<AgreementCompletedEvent.InputTuple, AgreementCompletedEvent.OutputTuple, AgreementCompletedEvent.OutputObject>;
    

      'AgreementDefaulted()': TypedContractEvent<AgreementDefaultedEvent.InputTuple, AgreementDefaultedEvent.OutputTuple, AgreementDefaultedEvent.OutputObject>;
      AgreementDefaulted: TypedContractEvent<AgreementDefaultedEvent.InputTuple, AgreementDefaultedEvent.OutputTuple, AgreementDefaultedEvent.OutputObject>;
    

      'AgreementExpired()': TypedContractEvent<AgreementExpiredEvent.InputTuple, AgreementExpiredEvent.OutputTuple, AgreementExpiredEvent.OutputObject>;
      AgreementExpired: TypedContractEvent<AgreementExpiredEvent.InputTuple, AgreementExpiredEvent.OutputTuple, AgreementExpiredEvent.OutputObject>;
    

      'AgreementPending()': TypedContractEvent<AgreementPendingEvent.InputTuple, AgreementPendingEvent.OutputTuple, AgreementPendingEvent.OutputObject>;
      AgreementPending: TypedContractEvent<AgreementPendingEvent.InputTuple, AgreementPendingEvent.OutputTuple, AgreementPendingEvent.OutputObject>;
    

      'DepositClaimed(uint256,string)': TypedContractEvent<DepositClaimedEvent.InputTuple, DepositClaimedEvent.OutputTuple, DepositClaimedEvent.OutputObject>;
      DepositClaimed: TypedContractEvent<DepositClaimedEvent.InputTuple, DepositClaimedEvent.OutputTuple, DepositClaimedEvent.OutputObject>;
    

      'DepositLocked(uint256)': TypedContractEvent<DepositLockedEvent.InputTuple, DepositLockedEvent.OutputTuple, DepositLockedEvent.OutputObject>;
      DepositLocked: TypedContractEvent<DepositLockedEvent.InputTuple, DepositLockedEvent.OutputTuple, DepositLockedEvent.OutputObject>;
    

      'DepositReleased(uint256)': TypedContractEvent<DepositReleasedEvent.InputTuple, DepositReleasedEvent.OutputTuple, DepositReleasedEvent.OutputObject>;
      DepositReleased: TypedContractEvent<DepositReleasedEvent.InputTuple, DepositReleasedEvent.OutputTuple, DepositReleasedEvent.OutputObject>;
    

      'LandlordApproved(address)': TypedContractEvent<LandlordApprovedEvent.InputTuple, LandlordApprovedEvent.OutputTuple, LandlordApprovedEvent.OutputObject>;
      LandlordApproved: TypedContractEvent<LandlordApprovedEvent.InputTuple, LandlordApprovedEvent.OutputTuple, LandlordApprovedEvent.OutputObject>;
    

      'LateFeeApplied(uint256,uint256)': TypedContractEvent<LateFeeAppliedEvent.InputTuple, LateFeeAppliedEvent.OutputTuple, LateFeeAppliedEvent.OutputObject>;
      LateFeeApplied: TypedContractEvent<LateFeeAppliedEvent.InputTuple, LateFeeAppliedEvent.OutputTuple, LateFeeAppliedEvent.OutputObject>;
    

      'RentPaid(uint256,uint256,uint256)': TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
      RentPaid: TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
    

      'TenantApproved(address)': TypedContractEvent<TenantApprovedEvent.InputTuple, TenantApprovedEvent.OutputTuple, TenantApprovedEvent.OutputObject>;
      TenantApproved: TypedContractEvent<TenantApprovedEvent.InputTuple, TenantApprovedEvent.OutputTuple, TenantApprovedEvent.OutputObject>;
    
    };
  }