/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface RentalAgreementFactoryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "activeRentals" | "agreementHistory" | "agreementOf" | "createRentalAgreement" | "getAgreementAt" | "getAgreementsCount" | "getRoleAdmin" | "grantRole" | "hasRole" | "isRegistered" | "latestAgreement" | "propertyNFT" | "registerActiveRental" | "renounceRole" | "rentalNFT" | "revokeRole" | "supportsInterface" | "unregisterActiveRental" | "usdcToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RentalAgreementCreated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'activeRentals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agreementHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agreementOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createRentalAgreement', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgreementAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgreementsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'latestAgreement', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propertyNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerActiveRental', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'rentalNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unregisterActiveRental', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activeRentals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agreementHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agreementOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createRentalAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgreementAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgreementsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerActiveRental', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentalNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unregisterActiveRental', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
  }

  
    export namespace RentalAgreementCreatedEvent {
      export type InputTuple = [agreementAddress: AddressLike, propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [agreementAddress: string, propertyId: bigint, tenant: string, baseRent: bigint, securityDeposit: bigint, deadline: bigint];
      export interface OutputObject {agreementAddress: string, propertyId: bigint, tenant: string, baseRent: bigint, securityDeposit: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RentalAgreementFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): RentalAgreementFactory;
    waitForDeployment(): Promise<this>;

    interface: RentalAgreementFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    activeRentals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    agreementHistory: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    agreementOf: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    createRentalAgreement: TypedContractMethod<
      [propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, inflationBps: BigNumberish, lateFeeBps: BigNumberish, gracePeriod: BigNumberish, duration: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    getAgreementAt: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getAgreementsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    latestAgreement: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    propertyNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerActiveRental: TypedContractMethod<
      [propertyId: BigNumberish, agreement: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rentalNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unregisterActiveRental: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'activeRentals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agreementHistory'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'agreementOf'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createRentalAgreement'): TypedContractMethod<
      [propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, inflationBps: BigNumberish, lateFeeBps: BigNumberish, gracePeriod: BigNumberish, duration: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgreementAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAgreementsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'latestAgreement'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'propertyNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerActiveRental'): TypedContractMethod<
      [propertyId: BigNumberish, agreement: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rentalNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unregisterActiveRental'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'RentalAgreementCreated'): TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'RentalAgreementCreated(address,uint256,address,uint256,uint256,uint256)': TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
      RentalAgreementCreated: TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }