# BlockRent — Android SDK setup (command-line tools only, no Android Studio)
#
# Usage (PowerShell):
#   cd android\smartlock-demo
#   .\scripts\setup-sdk.ps1
#
# Optional: pass a custom cmdline-tools folder
#   .\scripts\setup-sdk.ps1 -CmdlineToolsSource "C:\path\to\cmdline-tools"

param(
    [string]$CmdlineToolsSource = "C:\Users\loren\OneDrive\Desktop\commandlinetools-win-14742923_latest\cmdline-tools",
    [string]$SdkRoot = "$env:USERPROFILE\Android\sdk"
)

$ErrorActionPreference = "Stop"

function Write-Step([string]$Message) {
    Write-Host "`n==> $Message" -ForegroundColor Cyan
}

if (-not (Test-Path $CmdlineToolsSource)) {
    Write-Error "cmdline-tools not found at: $CmdlineToolsSource"
}

if (-not (Get-Command java -ErrorAction SilentlyContinue)) {
    Write-Error "Java not found. Install JDK 17+ (e.g. Temurin) and add it to PATH."
}

Write-Step "SDK root: $SdkRoot"
New-Item -ItemType Directory -Force -Path $SdkRoot | Out-Null

$latestDir = Join-Path $SdkRoot "cmdline-tools\latest"
if (-not (Test-Path $latestDir)) {
    Write-Step "Linking cmdline-tools into SDK layout"
    New-Item -ItemType Directory -Force -Path (Split-Path $latestDir -Parent) | Out-Null
    # Junction avoids copying; falls back to copy if junction fails
    try {
        cmd /c mklink /J "$latestDir" "$CmdlineToolsSource" | Out-Null
        Write-Host "Created junction: $latestDir -> $CmdlineToolsSource"
    } catch {
        Write-Host "Junction failed, copying files instead..."
        Copy-Item -Recurse -Force $CmdlineToolsSource $latestDir
    }
} else {
    Write-Host "cmdline-tools/latest already exists at $latestDir"
}

$env:ANDROID_HOME = $SdkRoot
$env:ANDROID_SDK_ROOT = $SdkRoot
$sdkmanager = Join-Path $latestDir "bin\sdkmanager.bat"

if (-not (Test-Path $sdkmanager)) {
    Write-Error "sdkmanager not found at $sdkmanager"
}

Write-Step "Accepting SDK licenses"
$yes = ("y`n" * 20)
$yes | & $sdkmanager --sdk_root=$SdkRoot --licenses | Out-Null

Write-Step "Installing SDK packages (platform-tools, platform 35, build-tools)"
& $sdkmanager --sdk_root=$SdkRoot "platform-tools" "platforms;android-35" "build-tools;35.0.0"

Write-Step "Writing local.properties"
$localProps = Join-Path $PSScriptRoot "..\local.properties"
$sdkDirEscaped = ($SdkRoot -replace "\\", "\\")
@"
## Generated by scripts/setup-sdk.ps1 — do not commit if it contains machine-specific paths
sdk.dir=$sdkDirEscaped
"@ | Set-Content -Path $localProps -Encoding UTF8

Write-Step "Done"
Write-Host @"

ANDROID_HOME=$SdkRoot

Add to your user PATH (Settings > Environment variables):
  $SdkRoot\platform-tools
  $SdkRoot\cmdline-tools\latest\bin

Next steps:
  1. Install Gradle (scoop install gradle) OR run: gradle wrapper --gradle-version 8.7
  2. Build:  .\gradlew.bat assembleDebug
  3. Install: adb install -r app\build\outputs\apk\debug\app-debug.apk

"@ -ForegroundColor Green
