/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPropertyNFT } from './IPropertyNFT.js';
export type { IRentalAgreement } from './IRentalAgreement.js';
export type { IRentalAgreementFactory } from './IRentalAgreementFactory.js';
export type { IRentalNFT } from './IRentalNFT.js';