/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRentalAgreementFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createRentalAgreement"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RentalAgreementCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createRentalAgreement', values: [AddressLike, BigNumberish, AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createRentalAgreement', data: BytesLike): Result;
  }

  
    export namespace RentalAgreementCreatedEvent {
      export type InputTuple = [agreementAddress: AddressLike, propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [agreementAddress: string, propertyId: bigint, tenant: string, baseRent: bigint, securityDeposit: bigint, deadline: bigint];
      export interface OutputObject {agreementAddress: string, propertyId: bigint, tenant: string, baseRent: bigint, securityDeposit: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRentalAgreementFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRentalAgreementFactory;
    waitForDeployment(): Promise<this>;

    interface: IRentalAgreementFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createRentalAgreement: TypedContractMethod<
      [propertyNFT: AddressLike, propertyId: BigNumberish, tenant: AddressLike, usdcToken: AddressLike, rentalNFT: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, inflationBps: BigNumberish, lateFeeBps: BigNumberish, gracePeriod: BigNumberish, duration: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createRentalAgreement'): TypedContractMethod<
      [propertyNFT: AddressLike, propertyId: BigNumberish, tenant: AddressLike, usdcToken: AddressLike, rentalNFT: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, inflationBps: BigNumberish, lateFeeBps: BigNumberish, gracePeriod: BigNumberish, duration: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >;

    getEvent(key: 'RentalAgreementCreated'): TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;

    filters: {
      
      'RentalAgreementCreated(address,uint256,address,uint256,uint256,uint256)': TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
      RentalAgreementCreated: TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
    
    };
  }