/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRentalAgreementInterface extends Interface {
    getFunction(nameOrSignature: "approveAgreement" | "baseRent" | "cancelAgreement" | "claimDeposit" | "completeAgreement" | "deadline" | "declareDefault" | "depositStatus" | "duration" | "gracePeriod" | "inflationBps" | "landlord" | "landlordApproved" | "lateFeeBps" | "payRent" | "paymentPeriod" | "propertyId" | "propertyNFT" | "releaseDeposit" | "rentPaidUntil" | "rentalNFT" | "securityDeposit" | "startTime" | "status" | "tenant" | "tenantApproved" | "usdcToken" | "withdrawRent"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'approveAgreement', values?: undefined): string;
encodeFunctionData(functionFragment: 'baseRent', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelAgreement', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimDeposit', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'completeAgreement', values?: undefined): string;
encodeFunctionData(functionFragment: 'deadline', values?: undefined): string;
encodeFunctionData(functionFragment: 'declareDefault', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'duration', values?: undefined): string;
encodeFunctionData(functionFragment: 'gracePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'inflationBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlord', values?: undefined): string;
encodeFunctionData(functionFragment: 'landlordApproved', values?: undefined): string;
encodeFunctionData(functionFragment: 'lateFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'payRent', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyId', values?: undefined): string;
encodeFunctionData(functionFragment: 'propertyNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'rentPaidUntil', values?: undefined): string;
encodeFunctionData(functionFragment: 'rentalNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'securityDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'startTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenant', values?: undefined): string;
encodeFunctionData(functionFragment: 'tenantApproved', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawRent', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approveAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'declareDefault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'duration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'gracePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inflationBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlordApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lateFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentPaidUntil', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentalNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'securityDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenantApproved', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRent', data: BytesLike): Result;
  }

  

  export interface IRentalAgreement extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRentalAgreement;
    waitForDeployment(): Promise<this>;

    interface: IRentalAgreementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveAgreement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    baseRent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelAgreement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimDeposit: TypedContractMethod<
      [amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    completeAgreement: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deadline: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    declareDefault: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    depositStatus: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    duration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    gracePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    inflationBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    landlord: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    landlordApproved: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lateFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    payRent: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paymentPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    propertyId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    propertyNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseDeposit: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rentPaidUntil: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rentalNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    securityDeposit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    startTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tenant: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tenantApproved: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawRent: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveAgreement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'baseRent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelAgreement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimDeposit'): TypedContractMethod<
      [amount: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeAgreement'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deadline'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'declareDefault'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositStatus'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'duration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'gracePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'inflationBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'landlord'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'landlordApproved'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lateFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'payRent'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paymentPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'propertyId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'propertyNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseDeposit'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rentPaidUntil'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rentalNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'securityDeposit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tenant'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tenantApproved'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawRent'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }