/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRentalAgreementFactoryInterface extends Interface {
    getFunction(nameOrSignature: "activeRentals" | "agreementHistory" | "agreementOf" | "createRentalAgreement" | "getAgreementAt" | "getAgreementsCount" | "isRegistered" | "latestAgreement" | "propertyNFT" | "registerActiveRental" | "rentalNFT" | "unregisterActiveRental" | "usdcToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RentalAgreementCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'activeRentals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agreementHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'agreementOf', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createRentalAgreement', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgreementAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgreementsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'latestAgreement', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'propertyNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerActiveRental', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'rentalNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'unregisterActiveRental', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'activeRentals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agreementHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'agreementOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createRentalAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgreementAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgreementsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAgreement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerActiveRental', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentalNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unregisterActiveRental', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
  }

  
    export namespace RentalAgreementCreatedEvent {
      export type InputTuple = [agreementAddress: AddressLike, propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [agreementAddress: string, propertyId: bigint, tenant: string, baseRent: bigint, securityDeposit: bigint, deadline: bigint];
      export interface OutputObject {agreementAddress: string, propertyId: bigint, tenant: string, baseRent: bigint, securityDeposit: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRentalAgreementFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRentalAgreementFactory;
    waitForDeployment(): Promise<this>;

    interface: IRentalAgreementFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeRentals: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    agreementHistory: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    agreementOf: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    createRentalAgreement: TypedContractMethod<
      [propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, inflationBps: BigNumberish, lateFeeBps: BigNumberish, gracePeriod: BigNumberish, duration: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    getAgreementAt: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getAgreementsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [agreement: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    latestAgreement: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    propertyNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerActiveRental: TypedContractMethod<
      [propertyId: BigNumberish, agreement: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rentalNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unregisterActiveRental: TypedContractMethod<
      [propertyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeRentals'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'agreementHistory'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'agreementOf'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createRentalAgreement'): TypedContractMethod<
      [propertyId: BigNumberish, tenant: AddressLike, baseRent: BigNumberish, securityDeposit: BigNumberish, inflationBps: BigNumberish, lateFeeBps: BigNumberish, gracePeriod: BigNumberish, duration: BigNumberish, deadline: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgreementAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAgreementsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [agreement: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'latestAgreement'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'propertyNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerActiveRental'): TypedContractMethod<
      [propertyId: BigNumberish, agreement: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rentalNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unregisterActiveRental'): TypedContractMethod<
      [propertyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'RentalAgreementCreated'): TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;

    filters: {
      
      'RentalAgreementCreated(address,uint256,address,uint256,uint256,uint256)': TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
      RentalAgreementCreated: TypedContractEvent<RentalAgreementCreatedEvent.InputTuple, RentalAgreementCreatedEvent.OutputTuple, RentalAgreementCreatedEvent.OutputObject>;
    
    };
  }