/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRentalAgreementFactory, IRentalAgreementFactoryInterface } from "../../interfaces/IRentalAgreementFactory.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "agreementAddress",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "propertyId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "tenant",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "baseRent",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "securityDeposit",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "RentalAgreementCreated",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "propertyNFT",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "propertyId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "tenant",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "usdcToken",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "rentalNFT",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "baseRent",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "securityDeposit",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "inflationBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lateFeeBps",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "gracePeriod",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "duration",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "deadline",
        "type": "uint256"
      }
    ],
    "name": "createRentalAgreement",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IRentalAgreementFactory__factory {
    static readonly abi = _abi;
    static createInterface(): IRentalAgreementFactoryInterface {
      return new Interface(_abi) as IRentalAgreementFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRentalAgreementFactory {
      return new Contract(address, _abi, runner) as unknown as IRentalAgreementFactory;
    }
  }
  